apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-application
  template:
    metadata:
      labels:
        app: example-application
    spec:
      containers:
      - image: Wade-fang/gitops-wade-test:v1.0.3:v1.0.3
        name: gitops-wade-test
      - image: docker-repo-name/example-application:v1.16.5
        name: example-application
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dockerhub
apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-application
  name: example-application
spec:
  ports:
  - port: 8080
  selector:
    app: example-application
  template:
    spec:
      containers:
      - image: Wade-fang/gitops-wade-test:v1.0.3:v1.0.3
        name: gitops-wade-test
  type: LoadBalancer
