apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-application
  template:
    metadata:
      labels:
        app: example-application
    spec:
      containers:
        - image: docker-repo-name/example-application:v1.16.5
          name: example-application
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockerhub
---
apiVersion: v1
kind: Service
metadata:
  name: example-application
  labels:
    app: example-application
spec:
  type: LoadBalancer
  selector:
    app: example-application
  ports:
    - port: 8080
